---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - domain_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined

- name: Create the files directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files"
    state: directory
    mode: 0700

- name: Create the docker-pleroma directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/docker-pleroma"
    state: directory
    mode: 0700

- name: Clone docker pleroma
  git:
    repo: 'https://github.com/angristan/docker-pleroma.git'
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/docker-pleroma"
    version: master

- name: Build docker image
  docker_image:
    name: pleroma
    build:
      path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/docker-pleroma"
      cache_from:
        - pleroma:latest
    source: build

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "pleroma:latest"
    memory: "200MB"
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}"
    exposed_ports:
      - "4000"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      VIRTUAL_HOST: "{{ domain_name }}"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "9000"
